INSERT INTO dbo.Area (Area) VALUES ('UBC')
INSERT INTO dbo.Area (Area) VALUES ('Burnaby')
INSERT INTO dbo.Area (Area) VALUES ('Coquitlam')
INSERT INTO dbo.Area (Area) VALUES ('Delta')
INSERT INTO dbo.Area (Area) VALUES ('North Vancouver')
INSERT INTO dbo.Area (Area) VALUES ('Richmond')
INSERT INTO dbo.Area (Area) VALUES ('Surrey')
INSERT INTO dbo.Area (Area) VALUES ('Vancouver')