//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.String", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string btn_comment {
            get {
                return ResourceManager.GetString("btn_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment/Offer.
        /// </summary>
        internal static string btn_commentoroffer {
            get {
                return ResourceManager.GetString("btn_commentoroffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btn_confirm {
            get {
                return ResourceManager.GetString("btn_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        internal static string btn_editaccount {
            get {
                return ResourceManager.GetString("btn_editaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btn_login {
            get {
                return ResourceManager.GetString("btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string btn_next {
            get {
                return ResourceManager.GetString("btn_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string btn_no {
            get {
                return ResourceManager.GetString("btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        internal static string btn_offer {
            get {
                return ResourceManager.GetString("btn_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Mail.
        /// </summary>
        internal static string btn_resendmail {
            get {
                return ResourceManager.GetString("btn_resendmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string btn_signup {
            get {
                return ResourceManager.GetString("btn_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string btn_yes {
            get {
                return ResourceManager.GetString("btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand New.
        /// </summary>
        internal static string ddl_cdbrandnew {
            get {
                return ResourceManager.GetString("ddl_cdbrandnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        internal static string ddl_cdexcellent {
            get {
                return ResourceManager.GetString("ddl_cdexcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        internal static string ddl_cdfair {
            get {
                return ResourceManager.GetString("ddl_cdfair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string ddl_cdgood {
            get {
                return ResourceManager.GetString("ddl_cdgood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        internal static string ddl_cdpoor {
            get {
                return ResourceManager.GetString("ddl_cdpoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Textbooks.
        /// </summary>
        internal static string hp_buytextbooks {
            get {
                return ResourceManager.GetString("hp_buytextbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string hp_home {
            get {
                return ResourceManager.GetString("hp_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string hp_login {
            get {
                return ResourceManager.GetString("hp_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string hp_logout {
            get {
                return ResourceManager.GetString("hp_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string hp_myaccount {
            get {
                return ResourceManager.GetString("hp_myaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Listing.
        /// </summary>
        internal static string hp_mylisting {
            get {
                return ResourceManager.GetString("hp_mylisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map preview.
        /// </summary>
        internal static string hp_previewmap {
            get {
                return ResourceManager.GetString("hp_previewmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Textbooks.
        /// </summary>
        internal static string hp_selltextbooks {
            get {
                return ResourceManager.GetString("hp_selltextbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string hp_signup {
            get {
                return ResourceManager.GetString("hp_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as {0}.
        /// </summary>
        internal static string lb_logininfo {
            get {
                return ResourceManager.GetString("lb_logininfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string lt_account {
            get {
                return ResourceManager.GetString("lt_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account info is listed below:.
        /// </summary>
        internal static string lt_account_description {
            get {
                return ResourceManager.GetString("lt_account_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation.
        /// </summary>
        internal static string lt_activation {
            get {
                return ResourceManager.GetString("lt_activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We apologize for the inconvenience, but an error has occurred during activation. It could be that the server is too busy at the moment, you have not registered for an account, or the website has encountered some internal error.&lt;br /&gt;Please register again or wait a few minutes then try again..
        /// </summary>
        internal static string lt_activation_description_fail {
            get {
                return ResourceManager.GetString("lt_activation_description_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully activated. Would you like to &lt;a href=&quot;login&quot;&gt;login now&lt;/a&gt;?.
        /// </summary>
        internal static string lt_activation_description_success {
            get {
                return ResourceManager.GetString("lt_activation_description_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string lt_area {
            get {
                return ResourceManager.GetString("lt_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author(s).
        /// </summary>
        internal static string lt_author {
            get {
                return ResourceManager.GetString("lt_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string lt_authors {
            get {
                return ResourceManager.GetString("lt_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there are more than one author, please delimit them with &apos;/&apos;.&lt;br /&gt;(ie. &quot;John Kauffman/Kevin Spencer/Thearon Willis&quot;).
        /// </summary>
        internal static string lt_author_description {
            get {
                return ResourceManager.GetString("lt_author_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding.
        /// </summary>
        internal static string lt_binding {
            get {
                return ResourceManager.GetString("lt_binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha Verification.
        /// </summary>
        internal static string lt_captchaverification {
            get {
                return ResourceManager.GetString("lt_captchaverification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the characters you see in the picture below..
        /// </summary>
        internal static string lt_captcha_description {
            get {
                return ResourceManager.GetString("lt_captcha_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer/Comment.
        /// </summary>
        internal static string lt_comments {
            get {
                return ResourceManager.GetString("lt_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string lt_condition {
            get {
                return ResourceManager.GetString("lt_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Textbook.
        /// </summary>
        internal static string lt_confirmtb {
            get {
                return ResourceManager.GetString("lt_confirmtb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the following book match the one you want to list?.
        /// </summary>
        internal static string lt_confirmtb_description {
            get {
                return ResourceManager.GetString("lt_confirmtb_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Code.
        /// </summary>
        internal static string lt_coursecode {
            get {
                return ResourceManager.GetString("lt_coursecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample course code: MATH122.
        /// </summary>
        internal static string lt_coursecode_description {
            get {
                return ResourceManager.GetString("lt_coursecode_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string lt_displayname {
            get {
                return ResourceManager.GetString("lt_displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your display name will be the only information shown to other visitors..
        /// </summary>
        internal static string lt_displayname_description {
            get {
                return ResourceManager.GetString("lt_displayname_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        internal static string lt_editaccount {
            get {
                return ResourceManager.GetString("lt_editaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Both your email address and display name should be unique per account..
        /// </summary>
        internal static string lt_editaccount_description {
            get {
                return ResourceManager.GetString("lt_editaccount_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string lt_edition {
            get {
                return ResourceManager.GetString("lt_edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string lt_emailaddress {
            get {
                return ResourceManager.GetString("lt_emailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email Address.
        /// </summary>
        internal static string lt_emailaddress_confirm {
            get {
                return ResourceManager.GetString("lt_emailaddress_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address will serve as an &lt;i&gt;unique&lt;/i&gt; username..
        /// </summary>
        internal static string lt_emailaddress_description {
            get {
                return ResourceManager.GetString("lt_emailaddress_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string lt_isbn {
            get {
                return ResourceManager.GetString("lt_isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN consists of 10 or 13 numeric characters with no dashes in-between. For more info, click &lt;a href=&quot;isbn&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        internal static string lt_isbn_description {
            get {
                return ResourceManager.GetString("lt_isbn_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The International Standard Book Number (ISBN) is a unique commercial book identifier barcode.&lt;br /&gt;Each ISBN code identifies uniquely a book. ISBN have either 10 or 13 digits.&lt;br /&gt;All ISBN assigned after 1 Jan 2007 have 13 digits.&lt;br /&gt;Typically, the ISBN is printed on the back cover of the book..
        /// </summary>
        internal static string lt_isbn_details {
            get {
                return ResourceManager.GetString("lt_isbn_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Details.
        /// </summary>
        internal static string lt_listdetails {
            get {
                return ResourceManager.GetString("lt_listdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Location.
        /// </summary>
        internal static string lt_location {
            get {
                return ResourceManager.GetString("lt_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an intersection or an address for the location to show up on Google Map.&lt;br /&gt;(41st Ave &amp; Granville Street, for example)&lt;br /&gt;We strongly recommend you to preview your address on Google map to ensure that it is presentable..
        /// </summary>
        internal static string lt_location_description {
            get {
                return ResourceManager.GetString("lt_location_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lt_login {
            get {
                return ResourceManager.GetString("lt_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login has failed.&lt;br /&gt;Please make sure that your email address and password are correct before trying again.&lt;br /&gt;If that doesn&apos;t work, please make sure that you have activated your account by clicking on the activation link in the sent mail..
        /// </summary>
        internal static string lt_loginfailed {
            get {
                return ResourceManager.GetString("lt_loginfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login in order to list your textbooks.&lt;br /&gt;Don&apos;t have an account? Please &lt;a href=&quot;signup&quot;&gt;sign up&lt;/a&gt; first..
        /// </summary>
        internal static string lt_login_description {
            get {
                return ResourceManager.GetString("lt_login_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string lt_manufacturer {
            get {
                return ResourceManager.GetString("lt_manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Listing.
        /// </summary>
        internal static string lt_mylisting {
            get {
                return ResourceManager.GetString("lt_mylisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below lies the complete record of your listing..
        /// </summary>
        internal static string lt_mylisting_description {
            get {
                return ResourceManager.GetString("lt_mylisting_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string lt_na {
            get {
                return ResourceManager.GetString("lt_na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string lt_notes {
            get {
                return ResourceManager.GetString("lt_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put other info related to your textbook here.&lt;br /&gt;For example, you may wish to indicate whether or not it contains a CD and so on.&lt;br /&gt;However, do note that your notes will be truncated when they exceed 300 characters..
        /// </summary>
        internal static string lt_notes_description {
            get {
                return ResourceManager.GetString("lt_notes_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Offers.
        /// </summary>
        internal static string lt_numberofoffers {
            get {
                return ResourceManager.GetString("lt_numberofoffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer/Comment.
        /// </summary>
        internal static string lt_offercomments {
            get {
                return ResourceManager.GetString("lt_offercomments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lt_password {
            get {
                return ResourceManager.GetString("lt_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string lt_password_confirm {
            get {
                return ResourceManager.GetString("lt_password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster.
        /// </summary>
        internal static string lt_posterdisplayname {
            get {
                return ResourceManager.GetString("lt_posterdisplayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string lt_price {
            get {
                return ResourceManager.GetString("lt_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference price from Amazon.ca: ${0:F2}&lt;br /&gt;Money sign is not allowed for the above field..
        /// </summary>
        internal static string lt_refprice {
            get {
                return ResourceManager.GetString("lt_refprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Price(Amazon.ca).
        /// </summary>
        internal static string lt_refprices {
            get {
                return ResourceManager.GetString("lt_refprices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may need to reload the page for your comment or offer to show up. Please refrain from posting repeated comments..
        /// </summary>
        internal static string lt_reload {
            get {
                return ResourceManager.GetString("lt_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string lt_rememberme {
            get {
                return ResourceManager.GetString("lt_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lt_search {
            get {
                return ResourceManager.GetString("lt_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Textbooks.
        /// </summary>
        internal static string lt_sell {
            get {
                return ResourceManager.GetString("lt_sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List your textbooks on UBCTextbooks for others to see..
        /// </summary>
        internal static string lt_sell_description {
            get {
                return ResourceManager.GetString("lt_sell_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the verification mail has not been sent to you after 10 minutes, please click on the button below to resend it..
        /// </summary>
        internal static string lt_sendmail {
            get {
                return ResourceManager.GetString("lt_sendmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string lt_signup {
            get {
                return ResourceManager.GetString("lt_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your UBCTextbooks Account gives you access to selling textbooks. If you already have a UBCTextbooks Account, you can &lt;a href=&quot;login&quot;&gt;login here&lt;/a&gt;..
        /// </summary>
        internal static string lt_signup_description {
            get {
                return ResourceManager.GetString("lt_signup_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-Digit: {0}/13-Digit: {1}.
        /// </summary>
        internal static string lt_tenorthirteendigit {
            get {
                return ResourceManager.GetString("lt_tenorthirteendigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Listed.
        /// </summary>
        internal static string lt_timelisted {
            get {
                return ResourceManager.GetString("lt_timelisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Posted.
        /// </summary>
        internal static string lt_timeposted {
            get {
                return ResourceManager.GetString("lt_timeposted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lt_title {
            get {
                return ResourceManager.GetString("lt_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string lt_userdetails {
            get {
                return ResourceManager.GetString("lt_userdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string lt_verification {
            get {
                return ResourceManager.GetString("lt_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address needs to be validated for our services.&lt;br /&gt;An email has been sent to &lt;i&gt;{0}&lt;/i&gt;. Please click on the link provided in it to activate your account..
        /// </summary>
        internal static string lt_verification_description {
            get {
                return ResourceManager.GetString("lt_verification_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for signing up at UBCTextbooks.ca. Please click on the link below to activate your account.&lt;br /&gt;If you cannot click on the link, please copy and paste it into your browser&apos;s address area and hit Enter..
        /// </summary>
        internal static string mail_verificationbody {
            get {
                return ResourceManager.GetString("mail_verificationbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Verification.
        /// </summary>
        internal static string mail_verificationsubject {
            get {
                return ResourceManager.GetString("mail_verificationsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The characters you entered didn&apos;t match the captcha verification..
        /// </summary>
        internal static string msg_captchanotmatch {
            get {
                return ResourceManager.GetString("msg_captchanotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Your display name must only contain alphabets, numbers or underscores and requires 3 ~ 12 characters..
        /// </summary>
        internal static string msg_displaynotvalid {
            get {
                return ResourceManager.GetString("msg_displaynotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Your email address is invalid..
        /// </summary>
        internal static string msg_emailnotvalid {
            get {
                return ResourceManager.GetString("msg_emailnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Your input does not match..
        /// </summary>
        internal static string msg_inputnotmatch {
            get {
                return ResourceManager.GetString("msg_inputnotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal has occurred. Please navigate to the previous page and resubmit your info..
        /// </summary>
        internal static string msg_internalerrortb {
            get {
                return ResourceManager.GetString("msg_internalerrortb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 10 or 13 numeric characters are allowed..
        /// </summary>
        internal static string msg_isbnnotvalid {
            get {
                return ResourceManager.GetString("msg_isbnnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find .
        /// </summary>
        internal static string msg_mapinserterror {
            get {
                return ResourceManager.GetString("msg_mapinserterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Course number may only contain 2 ~ 4 numeric characters..
        /// </summary>
        internal static string msg_numbernotvalid {
            get {
                return ResourceManager.GetString("msg_numbernotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Your password must only contain alphabets, numbers or underscores and requires 6 ~ 15 characters..
        /// </summary>
        internal static string msg_passwordnotvalid {
            get {
                return ResourceManager.GetString("msg_passwordnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your price is not in a valid format or too large.&lt;br /&gt;Sample price format: 79.99, 80.&lt;br /&gt;The price should not exceed 999 dollars..
        /// </summary>
        internal static string msg_pricenotvalid {
            get {
                return ResourceManager.GetString("msg_pricenotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *An account with this email address or display name has already been created..
        /// </summary>
        internal static string msg_repeatedemailorname {
            get {
                return ResourceManager.GetString("msg_repeatedemailorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This is a required field..
        /// </summary>
        internal static string msg_requiredfield {
            get {
                return ResourceManager.GetString("msg_requiredfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBCTextbooks.
        /// </summary>
        internal static string pagetitle {
            get {
                return ResourceManager.GetString("pagetitle", resourceCulture);
            }
        }
    }
}
